### PR TITLE
fix: call instance.off() before bind event handler even if equals. (fix #19)

### LINKED ISSUE #19: bindEventHandlers is never off event when use useCallback hook.
## Version
- @toast-ui/react-calendar: 1.0.4

## Test Environment
- macOS 10.14.6
- chrome 76

## Current Behavior
- reproduce: [https://codesandbox.io/s/white-moon-xe6zw](https://codesandbox.io/s/white-moon-xe6zw)
- There is `onClickSchedule` event handler that wrapped with useCallback hook.
- Click test schedule. alert is display just once.
- Click rerender button and click test schedule again. alert is display twice.

## Expected Behavior
- `onClickSchedule` should called only 1 time.

Please check `bindEventHandlers` method in `index.js`. there is a logic what compare event handlers with previous. I think it have to call `off()` before call `on()` every event handlers even if equals.

### PR DESCRIPTION
**Pull request by iamchanii**
### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by Alexis-Pannetier** [comment]
Please update this fix !

**Comment by iamchanii** [comment]
@Alexis-Pannetier I forgot this pr because it's so quiet! I guess they're busy for working 2.0 so maybe this will be not merge as soon as possible. but you still have the ways.

1. Fork this repository and cherry-pick this commit (or update manually). the solution as fastest as you can apply.
2. I mentioned, write your function as inline. (but I think this is not fit your mind or "React Spirit")

File: src/index.js [hunk 1]
```diff
@@ -110,18 +110,15 @@ export default class Calendar extends React.Component {
...
     const eventHandlerNames = Object.keys(props).filter((key) => /on[A-Z][a-zA-Z]+/.test(key));
 
     eventHandlerNames.forEach((key) => {
       const eventName = key[2].toLowerCase() + key.slice(3);
-      // For <Calendar onFocus={condition ? onFocus1 : onFocus2} />
-      if (prevProps && prevProps[key] !== props[key]) {
-        this.calendarInst.off(eventName);
-      }
+      this.calendarInst.off(eventName);
       this.calendarInst.on(eventName, this.props[key]);
```
Comment (jungeun-cho) [inline src/index.js]: @iamchanii 
You should use `props`.
```
this.calendarInst.on(eventName, props[key]);
```

The `props`(nextProps) is passed from `shouldComponentUpdate` and `this.props` will be the previous property.


```
<Calendar onFocus={condition ? onFocus1 : onFocus2}
```
If you need to bind a handler that you need dynamically, as in the code below, it will not work correctly the first time.
